CREATE TABLE IF NOT EXISTS `spring_session` (
    `PRIMARY_ID` char(36) COLLATE utf8_unicode_ci NOT NULL,
    `SESSION_ID` char(36) COLLATE utf8_unicode_ci NOT NULL,
    `CREATION_TIME` bigint NOT NULL,
    `LAST_ACCESS_TIME` bigint NOT NULL,
    `MAX_INACTIVE_INTERVAL` int NOT NULL,
    `EXPIRY_TIME` bigint NOT NULL,
    `PRINCIPAL_NAME` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
    PRIMARY KEY (`PRIMARY_ID`),
    UNIQUE KEY `SPRING_SESSION_IX1` (`SESSION_ID`),
    KEY `SPRING_SESSION_IX2` (`EXPIRY_TIME`),
    KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;
COMMIT;

CREATE TABLE IF NOT EXISTS `spring_session_attributes` (
    `SESSION_PRIMARY_ID` char(36) COLLATE utf8_unicode_ci NOT NULL,
    `ATTRIBUTE_NAME` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
    `ATTRIBUTE_BYTES` blob NOT NULL,
    PRIMARY KEY (`SESSION_PRIMARY_ID`,`ATTRIBUTE_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;

ALTER TABLE `spring_session_attributes`
    ADD CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_PRIMARY_ID`) REFERENCES `spring_session` (`PRIMARY_ID`) ON DELETE CASCADE;
COMMIT;